const $=id=>document.getElementById(id);let current=null,busy=false,showColor=false,showWalk=false,loadedModel=null,globalBusy=false,submitting=false;const files={};
const stageNames={prepare:'Bilder vorbereiten',shape:'Geometrie erzeugen',uv:'UV-Flächen vorbereiten',paint:'Texturen erzeugen',bake:'Texturen auftragen',face:'Gesicht prüfen und verbessern',finalize:'GLB exportieren',rig:'Skelett und Hautgewichte erzeugen'};
function themeLabel(){const dark=document.documentElement.dataset.theme==='dark';$('themeToggle').textContent=dark?'☀ Hell':'☾ Dunkel';$('themeToggle').setAttribute('aria-label',dark?'Helles Design aktivieren':'Dunkles Design aktivieren')}
$('themeToggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('img2gilb-theme',next)}catch(e){}themeLabel()};themeLabel();
const stateNames={queued:'Startet',running:'In Arbeit',complete:'Fertig',failed:'Fehler',cancelled:'Abgebrochen',interrupted:'Unterbrochen'};
function error(message){$('error').textContent=message||'';$('error').hidden=!message}
async function api(path,data){const r=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-App-Token':window.APP_TOKEN},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'Anfrage fehlgeschlagen');return j}
const viewNames=['front','back','left','right'];
let draftDB=null,draftReady=false;
const draftOpen=new Promise((resolve,reject)=>{const request=indexedDB.open('img2gilb-draft',1);request.onupgradeneeded=()=>request.result.createObjectStore('draft');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
function setReference(name,file){if(files[name]?.url)URL.revokeObjectURL(files[name].url);const img=$(name).parentNode.querySelector('img');if(!file){delete files[name];img.hidden=true;img.removeAttribute('src');$(name).value='';return}const url=URL.createObjectURL(file);files[name]={file,url};img.src=url;img.hidden=false}
function draftSettings(){return Object.fromEntries(['quality','triangles','height','resolution','textures','face'].map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value]))}
function storeDraft(){if(!draftReady||!draftDB)return;const tx=draftDB.transaction('draft','readwrite');const images=Object.fromEntries(Object.entries(files).map(([name,v])=>[name,v.file]));tx.objectStore('draft').put({images,settings:draftSettings()},'current');tx.oncomplete=()=>{$('draftStatus').textContent=Object.keys(images).length?'Entwurf lokal gespeichert.':''};tx.onerror=()=>{$('draftStatus').textContent='Entwurf konnte nicht gespeichert werden. Bilder bleiben bis zum Schließen verfügbar.'}}
async function restoreDraft(){try{draftDB=await draftOpen;const record=await new Promise((resolve,reject)=>{const request=draftDB.transaction('draft').objectStore('draft').get('current');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});if(record){for(const name of viewNames)if(record.images?.[name] instanceof Blob)setReference(name,record.images[name]);for(const [id,value] of Object.entries(record.settings||{})){if(!['quality','triangles','height','resolution','textures','face'].includes(id))continue;if($(id).type==='checkbox')$(id).checked=!!value;else $(id).value=value}$('textures').onchange();$('draftStatus').textContent=Object.keys(files).length?'Entwurf wiederhergestellt.':''}}catch(e){$('draftStatus').textContent='Lokales Speichern ist in diesem Browser nicht verfügbar.'}finally{draftReady=true}}
for(const name of viewNames)$(name).onchange=()=>{const f=$(name).files[0];if(!f)return;if(f.size>12*1024*1024){error('Ein Bild darf höchstens 12 MB groß sein.');$(name).value='';return}setReference(name,f);error('');storeDraft()};
$('clearReferences').onclick=()=>{for(const name of viewNames)setReference(name,null);storeDraft();error('')};
for(const id of ['quality','triangles','height','resolution','textures','face'])$(id).addEventListener('change',storeDraft);
$('textures').onchange=()=>{$('resolution').disabled=!$('textures').checked;$('face').disabled=!$('textures').checked;if(!$('textures').checked)$('face').checked=false};
const dataURL=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
$('generate').onclick=async()=>{try{error('');if(!files.front)throw Error('Bitte zuerst ein Frontbild auswählen.');submitting=true;$('generate').disabled=true;const views={};for(const [name,v] of Object.entries(files)){if(v.file.size>12*1024*1024)throw Error('Ein Bild darf höchstens 12 MB groß sein.');views[name]=await dataURL(v.file)}const settings={quality:$('quality').value,triangles:Number($('triangles').value),height_cm:Number($('height').value),texture_size:Number($('resolution').value),textures:$('textures').checked,face:$('face').checked,rig:$('rig').checked&&!$('rig').disabled};const job=await api('/api/jobs',{views,settings});selectJob(job);await refreshHistory()}catch(e){error(e.message)}finally{submitting=false;$('generate').disabled=busy||globalBusy}};
function selectJob(job){const s=job.settings;if(s){$('quality').value=s.quality;$('triangles').value=s.triangles;$('height').value=s.height_cm;$('resolution').value=s.texture_size;$('textures').checked=s.textures;$('face').checked=s.face;$('textures').onchange()}current=job.id;localStorage.setItem('img2gilb-current',current);showColor=false;showWalk=false;$('preview').autoplay=false;$('walkPreview').textContent='Laufprobe starten';loadedModel=null;$('material').textContent='Nur Farbe anzeigen';render(job);document.querySelectorAll('#historyList button').forEach(b=>b.classList.toggle('selected',b.dataset.id===current))}
function render(j){busy=['queued','running'].includes(j.status);$('generate').disabled=busy||globalBusy||submitting;$('working').hidden=!busy;$('statusBadge').dataset.state=j.status;$('statusBadge').textContent=stateNames[j.status]||j.status;$('progressBox').hidden=false;$('stageLabel').textContent=stageNames[j.stage]||stateNames[j.status];$('progress').max=j.stages?.length||1;$('progress').value=j.completed_stages||0;if(j.stage_fraction)$('progress').value+=j.stage_fraction;const seconds=Math.max(0,Math.floor(((j.finished||Date.now()/1000)-(j.started||j.created))));$('elapsed').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;$('detail').textContent=j.error||j.detail||`Schritt ${(j.completed_stages||0)+1} von ${j.stages?.length||'…'}`;$('cancel').hidden=!busy;$('retry').hidden=!['failed','cancelled','interrupted'].includes(j.status);$('diagnostic').hidden=!['failed','cancelled','interrupted'].includes(j.status);$('diagnostic').href=`/api/jobs/${j.id}/log`;if(j.status==='complete'){const r=j.result;$('empty').hidden=true;$('preview').hidden=false;$('downloads').hidden=false;$('walkPreview').hidden=!r.preview_animation;const suffix=(showColor||showWalk)?'color':'model';const src=`/api/jobs/${j.id}/${suffix}`;if(loadedModel!==src){$('preview').src=src;loadedModel=src}$('stats').textContent=`${r.triangles.toLocaleString('de-DE')} Dreiecke · ${r.vertices.toLocaleString('de-DE')} Vertices · ${r.height_cm.toFixed(1)} cm · ${r.texture_size?r.texture_size+' px Texturen':'ohne Texturen'}${r.rigged?' · Rig: '+r.joints+' Gelenke':''}${r.face_status?' · Gesicht: '+(r.face_status==='processed'?'verbessert':'Original beibehalten'):''}`;$('saveGLB').href=`/api/jobs/${j.id}/model`;$('saveProject').href=`/api/jobs/${j.id}/project`;$('material').hidden=!r.texture_size||r.rigged}else{$('preview').hidden=true;$('empty').hidden=busy;$('downloads').hidden=true;$('stats').textContent=''}}
$('cancel').onclick=async()=>{try{render(await api(`/api/jobs/${current}/cancel`,{}))}catch(e){error(e.message)}};
$('retry').onclick=async()=>{try{error('');render(await api(`/api/jobs/${current}/retry`,{}))}catch(e){error(e.message)}};
$('material').onclick=async()=>{showColor=!showColor;$('material').textContent=showColor?'PBR anzeigen':'Nur Farbe anzeigen';render(await api(`/api/jobs/${current}`))};
$('preview').addEventListener('error',()=>error('Die Vorschau konnte das Modell nicht laden. Das GLB kann weiterhin gespeichert werden.'));
async function refreshHistory(){const jobs=await api('/api/jobs');globalBusy=jobs.some(j=>['queued','running'].includes(j.status));$('generate').disabled=busy||globalBusy||submitting;$('historyList').replaceChildren();for(const j of jobs){const b=document.createElement('button');b.dataset.id=j.id;b.classList.toggle('selected',j.id===current);b.textContent=`${j.label?j.label+' · ':''}${new Date(j.created*1000).toLocaleString('de-DE')} · ${j.views.length} Ansicht(en) · ${stateNames[j.status]||j.status}`;b.onclick=()=>selectJob(j);$('historyList').append(b)}if(!jobs.length)$('historyList').textContent='Noch keine Projekte.';return jobs}
(async()=>{try{const cfg=await api('/api/config');$('rig').title=cfg.rigging_reason;$('rig').disabled=!cfg.rigging;if(cfg.rigging){$('rig').closest('label').classList.remove('unavailable');$('rig').closest('label').querySelector('small').textContent='Skelett und Hautgewichte automatisch erstellen';$('rig').closest('label').querySelector('em').hidden=true}const jobs=await refreshHistory();const saved=localStorage.getItem('img2gilb-current');const j=jobs.find(x=>['queued','running'].includes(x.status))||jobs.find(x=>x.id===saved);if(j){selectJob(j);$('quality').value=j.settings.quality;$('triangles').value=j.settings.triangles;$('height').value=j.settings.height_cm;$('resolution').value=j.settings.texture_size;$('textures').checked=j.settings.textures;$('face').checked=j.settings.face;$('textures').onchange()}}catch(e){error('Lokaler Dienst nicht erreichbar: '+e.message)}finally{await restoreDraft()}})();
setInterval(async()=>{if(!current)return;try{const j=await api(`/api/jobs/${current}`);const wasBusy=busy;render(j);if(wasBusy&&!busy)await refreshHistory()}catch(e){error('Verbindung unterbrochen. Die Seite erneut laden, sobald der Dienst bereit ist.')}},1500);
setInterval(()=>refreshHistory().catch(()=>{}),10000);


$('walkPreview').onclick=async()=>{showWalk=!showWalk;$('preview').autoplay=showWalk;$('walkPreview').textContent=showWalk?'Laufprobe stoppen':'Laufprobe starten';render(await api(`/api/jobs/${current}`))};
$('preview').addEventListener('load',()=>{if(showWalk)$('preview').play()});
